MultiMillionaire/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MultiMillionaire.Models;

namespace MultiMillionaire.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MultiMillionaire/Controllers/MultiplayerController.cs
using Microsoft.AspNetCore.Mvc;
using Wangkanai.Detection.Models;
using Wangkanai.Detection.Services;

namespace MultiMillionaire.Controllers;

[Route("multiplayer")]
public class MultiplayerController : Controller
{
    private readonly IDetectionService _detectionService;

    public MultiplayerController(IDetectionService detectionService)
    {
        _detectionService = detectionService;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet("host")]
    public IActionResult Host()
    {
        ViewData["IsMobile"] = _detectionService.Device.Type == Device.Mobile;
        return View();
    }

    [HttpGet("audience")]
    public IActionResult Audience()
    {
        ViewData["IsMobile"] = _detectionService.Device.Type == Device.Mobile;
        return View();
    }

    [HttpGet("spectate")]
    public IActionResult Spectate()
    {
        ViewData["IsMobile"] = _detectionService.Device.Type == Device.Mobile;
        return View();
    }
}

MultiMillionaire/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<partial name="_MenuLogo"/>

<div>
    <div class="row mb-2">
        <hr class="col question-line my-auto px-0"/>
        <div class="col-md-auto question menu-button-lg disabled">Singleplayer</div>
        <hr class="col question-line my-auto px-0"/>
    </div>

    <div class="row mb-2">
        <hr class="col question-line my-auto px-0"/>
        <a asp-controller="Multiplayer" asp-action="Index" class="col-md-auto question menu-button-lg">Multiplayer</a>
        <hr class="col question-line my-auto px-0"/>
    </div>
</div>